name: Serverless Devs Project CI/CD

on:
  push:
    branches: [ serverless-devs ]

jobs:
  serverless-devs-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm install -g @serverless-devs/s
      # 默认密钥配置指令是阿里云密钥配置指令，更多可以参考：
      # 如何通过GitHub Action使用Serverless Devs做CI/CD：http://short.devsapp.cn/cicd/github/action/usage
      # Serverless Devs的官网是通过Serverless Devs部署的: http://short.devsapp.cn/cicd/github/action/practice
      - run: s config add --AccessKeyID ${{secrets.HW_ACCESS_KEY}} --SecretAccessKey ${{secrets.HW_SECRET_KEY}} -a default
      - run: s deploy                                