name: Deploy to FunctionGraph

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
        HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
        HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_SECRET_KEY }}
        HW_REGION_NAME: ${{ vars.HW_REGION }}
        BACKEND_BUCKET: ${{ vars.BACKEND_BUCKET }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend-config="bucket=$BACKEND_BUCKET" -backend-config="region=$HW_REGION_NAME" -backend-config="endpoint=https://obs.$HW_REGION_NAME.myhuaweicloud.com"

    - name: Terraform Apply
      run: terraform apply -auto-approve
      