name: Deploy to FunctionGraph

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
        HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
        HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_SECRET_KEY }}
        HW_REGION_NAME: ${{ secrets.HW_REGION }}
        TF_VAR_backend_bucket: ${{ vars.BACKEND_BUCKET }}
        TF_VAR_backend_region: ${{ secrets.HW_REGION }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      